services:
  stac-dev:
    image: pc-apis-stac-dev
    build:
      context: ../planetary-computer-apis
      dockerfile: pcstac/Dockerfile.dev
    environment:
      - ENVIRONMENT=development
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - PCAPIS_DEBUG=TRUE
      - TILER_HREF=http://localhost:8080/data/

      # Azure Storage
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_URL=http://azurite:10002/devstoreaccount1
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_NAME=devstoreaccount1
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - PCAPIS_COLLECTION_CONFIG__TABLE_NAME=collectionconfig

      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_URL=http://azurite:10002/devstoreaccount1
      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_NAME=devstoreaccount1
      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - PCAPIS_CONTAINER_CONFIG__TABLE_NAME=containerconfig

      - PCAPIS_IP_EXCEPTION_CONFIG__ACCOUNT_URL=http://azurite:10002/devstoreaccount1
      - PCAPIS_IP_EXCEPTION_CONFIG__ACCOUNT_NAME=devstoreaccount1
      - PCAPIS_IP_EXCEPTION_CONFIG__ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - PCAPIS_IP_EXCEPTION_CONFIG__TABLE_NAME=ipexceptionlist

      # Redis
      - PCAPIS_REDIS_HOSTNAME=redis
      - PCAPIS_REDIS_PASSWORD=devcache
      - PCAPIS_REDIS_PORT=6380
      - PCAPIS_REDIS_SSL=FALSE

      # Rate limit
      - PCAPIS_RATE_LIMITS__COLLECTIONS=1000
      - PCAPIS_RATE_LIMITS__COLLECTION=100
      - PCAPIS_RATE_LIMITS__ITEMS=1000
      - PCAPIS_RATE_LIMITS__ITEM=1000
      - PCAPIS_RATE_LIMITS__SEARCH=1000

      # Backpressure
      - PCAPIS_BACK_PRESSURES__COLLECTIONS__REQ_PER_SEC=100
      - PCAPIS_BACK_PRESSURES__COLLECTIONS__INC_MS=10
      - PCAPIS_BACK_PRESSURES__COLLECTION__REQ_PER_SEC=100
      - PCAPIS_BACK_PRESSURES__COLLECTION__INC_MS=10
      - PCAPIS_BACK_PRESSURES__ITEMS__REQ_PER_SEC=100
      - PCAPIS_BACK_PRESSURES__ITEMS__INC_MS=10
      - PCAPIS_BACK_PRESSURES__ITEM__REQ_PER_SEC=100
      - PCAPIS_BACK_PRESSURES__ITEM__INC_MS=10
      - PCAPIS_BACK_PRESSURES__SEARCH__REQ_PER_SEC=100
      - PCAPIS_BACK_PRESSURES__SEARCH__INC_MS=10
    volumes:
      - ../planetary-computer-apis:/opt/src
    command: >
      /bin/bash
    depends_on:
      - stac
